apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: suite
  labels:
    app: homebridge
spec:
  type: ClusterIP
  selector:
    app: homebridge
  ports:
    - name: ui
      port: 8581
      targetPort: 8581
      protocol: TCP
    - name: tls
      port: 51443
      targetPort: 51443
      protocol: TCP
