apiVersion: v1
data:
  02-suite-home-arpa.conf: |
    address=/suite.home.arpa/192.168.50.242
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"02-suite-home-arpa.conf":"address=/suite.home.arpa/192.168.50.242\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"pihole-dnsmasq","namespace":"suite"}}
  creationTimestamp: "2025-09-12T12:53:25Z"
  name: pihole-dnsmasq
  namespace: suite
  resourceVersion: "19077293"
  uid: 2d8c0421-b549-4c38-be4e-ec38728ce7ec
