apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suite

resources:
  - deployment.yaml
  - service.yaml
  - cm-dnsmasq.yaml
  - cm-ui-override.yaml
  - cm-dnsmasq-custom.yaml
  - pvc-etc-pihole.yaml
  - pvc-dnsmasq.yaml


