apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pihole-etc-pihole-pvc-longhorn","namespace":"suite"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"longhorn"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2025-10-17T13:11:41Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pihole-etc-pihole-pvc-longhorn
  namespace: suite
  resourceVersion: "22016701"
  uid: 65534ce8-dd40-4bae-b018-962dcb5638ee
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-65534ce8-dd40-4bae-b018-962dcb5638ee
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
