apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: suite
spec:
  ports:
  - name: ui
    port: 8581
    protocol: TCP
    targetPort: 8581
  # (note: we intentionally only supply ports here so strategic merge updates ports preserving selectors/clusterIP)
