apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"default","namespace":"metallb-system"},"spec":{"addresses":["192.168.50.241-192.168.50.250"]}}
    creationTimestamp: "2025-08-24T13:11:03Z"
    generation: 2
    name: default
    namespace: metallb-system
    resourceVersion: "35347886"
    uid: 1b222ee5-a5c0-4c72-a91c-b5b2fd6e857b
  spec:
    addresses:
    - 192.168.50.240-192.168.50.244
    - 192.168.50.246-192.168.50.249
    autoAssign: true
    avoidBuggyIPs: false
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"home-lan","namespace":"metallb-system"},"spec":{"addresses":["192.168.50.240-192.168.50.244"]}}
    creationTimestamp: "2025-11-13T15:58:31Z"
    generation: 1
    name: home-lan
    namespace: metallb-system
    resourceVersion: "35356473"
    uid: e4ff754f-b45a-4e38-84f5-f7aab69142e7
  spec:
    addresses:
    - 192.168.50.240-192.168.50.244
    autoAssign: true
    avoidBuggyIPs: false
kind: List
metadata:
  resourceVersion: ""
