apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"default","namespace":"metallb-system"},"spec":{"ipAddressPools":["default"]}}
    creationTimestamp: "2025-08-24T13:11:03Z"
    generation: 1
    name: default
    namespace: metallb-system
    resourceVersion: "1230967"
    uid: cf7c7729-e98b-402d-936e-3745fed036c1
  spec:
    ipAddressPools:
    - default
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"home-lan","namespace":"metallb-system"},"spec":{"ipAddressPools":["home-lan"]}}
    creationTimestamp: "2025-11-13T15:58:31Z"
    generation: 1
    name: home-lan
    namespace: metallb-system
    resourceVersion: "35356475"
    uid: 6ef7240e-d4c4-4d07-9b5b-6ef74dd25357
  spec:
    ipAddressPools:
    - home-lan
kind: List
metadata:
  resourceVersion: ""
